//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.github.TheCSUser.HideItBobby.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesSHA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesSHA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.github.TheCSUser.HideItBobby.Properties.ResourcesSHA", typeof(ResourcesSHA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5e26cfe3242c5157ecc579b2961f51539915075d5a00fa46b58e50b4c53273e7.
        /// </summary>
        internal static string hide_it_bobby_21_BOM_en_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_21_BOM_en_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f29d85c675c5666194d388d11b89834dc08bfd5a66d80df25c8cab5d2c58e8f1.
        /// </summary>
        internal static string hide_it_bobby_21_BOM_pl_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_21_BOM_pl_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2e2c2b8d771f10b5c1eb267ba776935d002e13cdf62c06389e7dc68362caebc9.
        /// </summary>
        internal static string hide_it_bobby_21_en_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_21_en_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e287e0335efccdcbc5d5cad747dfe893ed695eabe285e89abcc1426b772b496f.
        /// </summary>
        internal static string hide_it_bobby_21_pl_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_21_pl_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 953d079bec3142df374fc1dfa0338d1bbe08ef4eb8509a984e2f922a11f5f3f7.
        /// </summary>
        internal static string hide_it_bobby_22_BOM_de_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_22_BOM_de_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 173b87527320ccea203346c4f9ffd011b00959d037b1b17bcc734bd658f476d4.
        /// </summary>
        internal static string hide_it_bobby_22_BOM_pl_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_22_BOM_pl_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a17f58f85dc9e76049637ac6442f78c4d00a1462b336798b23c632eb2803aba3.
        /// </summary>
        internal static string hide_it_bobby_22_BOM_zh_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_22_BOM_zh_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 93d6ce564d3fb9e12b21e57b190fef8b9fbb31439decd0d3c9b77278fe15af07.
        /// </summary>
        internal static string hide_it_bobby_22_de_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_22_de_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02780fe089c7d54d02ff44ed73a962d119df07b766ec6ec320dc6b5715e1a938.
        /// </summary>
        internal static string hide_it_bobby_22_pl_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_22_pl_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5b9d75642586b5decd73d75ee1647494d87e225435cc4a2d668a6d67737c4eaa.
        /// </summary>
        internal static string hide_it_bobby_22_zh_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_22_zh_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ede84a9f62f0f10fc090f153e44e38aec8c5e7d11e02e9f0a63de72514ab8403.
        /// </summary>
        internal static string hide_it_bobby_23_BOM_ja_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_23_BOM_ja_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bb66c277e9c5710ce1ab11fca36f5a88f9ecf47d571c46d29e77712779f8a950.
        /// </summary>
        internal static string hide_it_bobby_23_ja_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_23_ja_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0348acd5a6c84a7ac7743b01ec5a039915d9cb4470d57b2ad896606e389cbcd8.
        /// </summary>
        internal static string hide_it_bobby_25_BOM_de_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_25_BOM_de_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4d3af3ceb929e27b0f004ba9b172692c7a1a0227dc72ae4960269f48bb23bbc1.
        /// </summary>
        internal static string hide_it_bobby_25_BOM_es_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_25_BOM_es_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d4fbdffad12a0b65175e71263d1205818bc1e55c2ca8b0a768622e02339dd9a5.
        /// </summary>
        internal static string hide_it_bobby_25_de_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_25_de_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7b3e986d0ab9de4fc7cf6152d323bd13442d02155c42469da1f299e3abf08e25.
        /// </summary>
        internal static string hide_it_bobby_25_es_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_25_es_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9251e44adfcfbba87ffd67a6423c9a22aea4c5150632fe7654b12a8bab4bec2c.
        /// </summary>
        internal static string hide_it_bobby_29_BOM_de_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_BOM_de_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6701e384f21686dff44ba6e5e8cc9f0b2707a6cdedf97164be603278ec1bca1d.
        /// </summary>
        internal static string hide_it_bobby_29_BOM_en_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_BOM_en_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f8f1fd16cb7b3d54896b04e895e5cfe7a1882570cdc9a6de7c590012fd0e652.
        /// </summary>
        internal static string hide_it_bobby_29_BOM_es_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_BOM_es_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e2ab8cc270b21e8dda665337667c4d940c26c60f18ea40b9dcd9f290a96ecbd7.
        /// </summary>
        internal static string hide_it_bobby_29_BOM_ja_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_BOM_ja_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90e7b725228725af151cfb72453253455a00f2d09a87c4fb24909e00fe47476e.
        /// </summary>
        internal static string hide_it_bobby_29_BOM_pl_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_BOM_pl_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a9ada746fbdb94ed2eefbf80904ceaa0e097bdc7b2c607a839a24b0faea8d204.
        /// </summary>
        internal static string hide_it_bobby_29_BOM_ru_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_BOM_ru_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06ee0528aa8ffc52ef8e60fbe248a6e71109f02dd08e934dd34f52979bd9b978.
        /// </summary>
        internal static string hide_it_bobby_29_BOM_zh_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_BOM_zh_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4303931cee350ecb25a2e78016d67820d042cac1562c93ce935df0c4cddecd08.
        /// </summary>
        internal static string hide_it_bobby_29_de_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_de_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9d94b0d0dfa2c1cd1cc72295e7940cf01de5e0c0d2550795a6fe321039d44cee.
        /// </summary>
        internal static string hide_it_bobby_29_en_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_en_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4d69d6ebc47ea39a598cd80cd5d00bdbd6656b1594ab1f72bfae0deaac963aac.
        /// </summary>
        internal static string hide_it_bobby_29_es_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_es_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10b112b9989ed5b991c0f4e30c8db0597c5e1998f0340940506d8db876e953fe.
        /// </summary>
        internal static string hide_it_bobby_29_ja_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_ja_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 653a871f0a34dbc7a4e5488d6d8199864a28447aab9cb16242dca562aeff80ea.
        /// </summary>
        internal static string hide_it_bobby_29_pl_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_pl_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e00dbc6b87b4303df1e20335907cc08ac93637e6788f07f7688db6dedce82d69.
        /// </summary>
        internal static string hide_it_bobby_29_ru_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_ru_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ab4d7e022a6d7b50833551548ec2919cf88c3f53959df628215ffeab0bd74599.
        /// </summary>
        internal static string hide_it_bobby_29_zh_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_29_zh_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9ac0921e54c78c3c06cdf43f3701df61c92dd0598bb98ec6aff4c2ff5e034efe.
        /// </summary>
        internal static string hide_it_bobby_30_BOM_en_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_30_BOM_en_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b4396aac24e52f1fb726bd1eddb5b5bea9ec385f482056beff4526e1f85d6006.
        /// </summary>
        internal static string hide_it_bobby_30_en_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_30_en_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 064fbf3c2b1c6745ad523d3108d26377aa5218add18df466950c8fc9993a8175.
        /// </summary>
        internal static string hide_it_bobby_31_en_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_31_en_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81f2b4df16abb1ddb82aee13b5440426fbf1990bfa230e087f1513364e2fe369.
        /// </summary>
        internal static string hide_it_bobby_31_ja_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_31_ja_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a5c987c84cdf36bfbb76895421f82f7a57a9a40c4e6c0f07a495a124919546d5.
        /// </summary>
        internal static string hide_it_bobby_31_ko_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_31_ko_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2f2406dff75675b8e34d24eaf7a4471aefb8637b4f69d47eb979e3e61343c45b.
        /// </summary>
        internal static string hide_it_bobby_32_ja_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_32_ja_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 505c03d1b7cba3ac7b35e8309d609940d46b2a3d9fd8a322fe20bbe238dd90e3.
        /// </summary>
        internal static string hide_it_bobby_33_pt_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_33_pt_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dca4595ffa2fe95fbec3cbf9b04083831ad66c47e086fda08fcbab4c94af6f54.
        /// </summary>
        internal static string hide_it_bobby_33_ru_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_33_ru_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f3712c2e204c67fb3dbc67a231786ff5db3fa061e998534b6f9c6a827f3d90ee.
        /// </summary>
        internal static string hide_it_bobby_34_de_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_34_de_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25d135e0ed30040ea4d03a082d19d46267256044980ab5a51697bbd3088f4561.
        /// </summary>
        internal static string hide_it_bobby_34_en_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_34_en_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d8a5473b4bffd0618f1ecdf50e1a8d357e5f7acc02f7b739bf7aedb7e85c9989.
        /// </summary>
        internal static string hide_it_bobby_34_es_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_34_es_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f0661d460c30cbf448b739696e026955b31dbd04da2684646c262e70fcfad555.
        /// </summary>
        internal static string hide_it_bobby_34_ja_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_34_ja_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4eefc4d898a418c933886cf2f26fd8ef81a519c73b7cd56d27095a712bfd2f5b.
        /// </summary>
        internal static string hide_it_bobby_34_ko_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_34_ko_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0d7959e86138b6d0a0868ad0665453fc6eb0c211988a6b17e4503ef92e983210.
        /// </summary>
        internal static string hide_it_bobby_34_pl_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_34_pl_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d6f7e786f49983fa2661a69fc5443fa08047e8a7ae9b431bb967bcf15ac9be66.
        /// </summary>
        internal static string hide_it_bobby_34_pt_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_34_pt_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9073857cf75162412a44796d68bd56669a3dbcb52c7dede636d65c7b866235ea.
        /// </summary>
        internal static string hide_it_bobby_34_ru_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_34_ru_sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3f0cf73e56095089ec66d7cafc17336ac86c158eda92d817d7a80bce77da9ba2.
        /// </summary>
        internal static string hide_it_bobby_34_zh_sha256 {
            get {
                return ResourceManager.GetString("hide_it_bobby_34_zh_sha256", resourceCulture);
            }
        }
    }
}
